/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.perpustakaan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Irfan Oesman Asa
 */
public class MenuAnggota extends javax.swing.JFrame {
    
    private Connection conn;
    private int idAnggota;
    private String namaAnggota;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuAnggota.class.getName());
    DefaultTableModel model;
    
    private void tampilRiwayatUser() {
    model.setRowCount(0); // Bersihkan isi tabel sebelum memuat data baru
    
    try {
        
        // Pastikan p.tanggal_jatuh_tempo ikut dipanggil di query SQL
        String sql = "SELECT p.id_peminjam, b.judul, p.tanggal_pinjam, p.tanggal_jatuh_tempo, p.tanggal_kembali, p.status " +
                     "FROM peminjaman p " +
                     "INNER JOIN buku b ON p.id_buku = b.id_buku " +
                     "WHERE p.id_anggota = ? " +
                     "ORDER BY p.id_peminjam DESC"; 
                     
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, this.idAnggota); 
        
        ResultSet rs = pst.executeQuery();
        while(rs.next()) {
            // 1. Cek tanggal_kembali, jika NULL tampilkan tanda strip (-)
            String tglKembali = rs.getString("tanggal_kembali");
            if (tglKembali == null) {
                tglKembali = "-";
            }
            
            // 2. Cek tanggal_jatuh_tempo, jika NULL tampilkan tanda strip (-)
            String tglJatuhTempo = rs.getString("tanggal_jatuh_tempo");
            if (tglJatuhTempo == null) {
                tglJatuhTempo = "-";
            }
            
            // 3. Ambil status transaksi ('dipinjam' / 'dikembalikan')
            String statusTransaksi = rs.getString("status");
            if (statusTransaksi == null || statusTransaksi.isEmpty()) {
                statusTransaksi = "-";
            }
            
            // 4. Susun data HARUS SEJAJAR dengan 6 kolom yang kita buat di Constructor
            Object[] data = {
                rs.getString("id_peminjam"),      // Kolom 1: ID Pinjam
                rs.getString("judul"),            // Kolom 2: Judul Buku
                rs.getString("tanggal_pinjam"),   // Kolom 3: Tanggal Pinjam
                tglJatuhTempo,                    // Kolom 4: Jatuh Tempo (Baru dimasukkan)
                tglKembali,                       // Kolom 5: Tanggal Kembali
                statusTransaksi                   // Kolom 6: Status ('dipinjam' atau 'dikembalikan')
            };
            
            model.addRow(data);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat riwayat transaksi: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    public MenuAnggota(int idLogin, String namaUser) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idAnggota = idLogin;
        this.namaAnggota = namaUser;
        
        lblNama.setText(namaAnggota);
        
        Object[] kolom = {"ID Pinjam", "Judul Buku", "Tanggal Pinjam", "Jatuh Tempo", "Tanggal Kembali", "Status"};
        model = new DefaultTableModel(null, kolom);
        tabel.setModel(model);
        
         Koneksi db = new Koneksi();
        this.conn = db.connect();
        if (this.conn == null) {
            JOptionPane.showMessageDialog(this, "Aplikasi gagal terhubung ke database!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        tampilRiwayatUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/account 32px.png"))); // NOI18N

        lblNama.setText("Nama");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dots 16px.png"))); // NOI18N
        jLabel6.setText("Online");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel1.setText("Riwayat Peminjaman");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama)
                                    .addComponent(jLabel6)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNama;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
